# Generated by Django 4.2.3 on 2023-07-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='Profileimage/defaul.jpg', null=True, upload_to='Profileimage'),
        ),
    ]
